language: php

os: linux

dist: xenial

addons:
  firefox: "47.0.1"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

services:
  - mysql
  - postgresql
  - docker

env:
  jobs:
   - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
   - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
   - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
   - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
   - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
   - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
   - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
   - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
   - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
   - DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE

jobs:
 exclude:
  - php: 7.0
    env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
  - php: 7.0
    env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
  - php: 7.0
    env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
  - php: 7.0
    env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
  - php: 7.3
    env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
  - php: 7.3
    env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
  - php: 7.3
    env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
  - php: 7.3
    env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
  - php: 7.3
    env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
  - php: 7.3
    env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
  - php: 7.4
    env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
  - php: 7.4
    env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
  - php: 7.4
    env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
  - php: 7.4
    env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
  - php: 7.4
    env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
  - php: 7.4
    env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
  - php: 7.4
    env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
  - php: 7.4
    env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
 fast_finish: true

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd || true # report issues, but don't fail the build.
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache || true # report issues, but don't fail the build.
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit --coverage-clover
  - moodle-plugin-ci behat

after_success:
  - moodle-plugin-ci coveralls-upload
